config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  root to: 'posts#index'
  # get 'genres/search' => 'genres#search'
  get 'posts/search' => 'posts#search',as: 'posts_search'
  get 'profile/:id' => 'users#profile',as: 'user_profile'
  post 'post/chapter_like' => 'chapter_likes#like',as: 'chapter_like'
  resources :comments 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  belongs_to :post
  has_rich_text :content
  has_many :chapter_likes

  def liked?(user)
  	ChapterLike.exists?(chapter_id: self.id,user_id: user.id)
  end
end

app/models/chapter_like.rb
class ChapterLike < ApplicationRecord
  belongs_to :chapter
  belongs_to :user


end

app/models/chpater.rb
class Chpater < ApplicationRecord
  belongs_to :post
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :post_genres
	has_many :posts, through: :post_genres
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :chapters,dependent: :destroy
	accepts_nested_attributes_for :chapters,allow_destroy: true
	has_one :post_genre
	has_one :genre,through: :post_genre
	has_many :comments,dependent: :destroy

end

app/models/post_genre.rb
class PostGenre < ApplicationRecord
  belongs_to :post
  belongs_to :genre
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable,:lockable
  has_many :posts
  has_many :comments
  has_one_attached :avatar
  has_many :chapter_likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

		def configure_permitted_parameters
			devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:avatar,:first_name,:last_name, :email, :password,:password_confirmation)}
			devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:avatar,:first_name,:last_name, :email, :password, :current_password)}
		end
end

app/controllers/chapter_likes_controller.rb
class ChapterLikesController < ApplicationController
	before_action :authenticate_user!
	def like
		if ChapterLike.exists?(chapter_id: params[:chapter_id],user_id: params[:user_id])
			redirect_to root_path
		else
			ChapterLike.create(chapter_id: params[:chapter_id],user_id: params[:user_id])
			redirect_to root_path
		end
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	def create
		post = Post.find(comment_params[:post_id])
		@comment = current_user.comments.create(comment_params)
		PostChannel.broadcast_to post, comment: @comment,user: current_user
	end

	private

	def comment_params
		params.require(:comment).permit(:content,:post_id)
	end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
	def search
		@genres = Genre.where('title LIKE ?','%' + params[:q] + '%')
		html = render_to_string(partial: 'autocomplete_results',locals: { genres: @genres})
		render json: { html: html } 
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!,only: [:new,:create,:edit,:update,:destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  def search
    @posts = Post.where('title LIKE ?','%' + params[:q] + '%')
  end
  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :summary,chapters_attributes: [:_destroy,:id,:title,:content])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def profile
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/genres/_autocomplete_results.html.erb
<% genres.each do |genre| %>
	<li role="option" data-autocomplete-value="<%= genre.id %>"><%= genre.title %></li>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Fan fix</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to 'Профиль',user_profile_path(current_user),class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Добавить пост',new_post_path,class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
    <form action="posts/search" class="form-inline my-2 my-lg-0" method="get">
      <input type="text" name="q" class="form-control">
      <button type="submit" class="btn btn-outline-success my-2 my-sm-0">Поиск</button>
    </form>
    

    <div class="ml-5">
      <% if user_signed_in? %>
        <%= link_to 'Выйти из аккаунта',destroy_user_session_path,method: :delete,class: 'btn btn-danger' %>
      <% else %>
        <%= link_to 'Войти',new_user_session_path,class: 'btn btn-success' %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fan fix</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_chapter_fields.html.erb
<div class="nested-fields">
	<div class="form-group">
		<%= form.hidden_field :_destroy %>
		<%= form.text_field :title,placeholder: 'Заголовок',class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= form.rich_text_area :content,class: 'form-control' %>
		<small>
			<%= link_to "Remove",'#',data: { action: 'click->nested-form#remove_association'} %>
		</small>
	</div>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title do %>
      Название
    <% end %>
    <%= form.text_field :title,class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :summary do %> 
      Краткое содержание
    <% end %>
    <%= form.text_area :summary,class: "form-control" %>
  </div>
  <div class="form-group">
    <div data-controller="autocomplete" data-autocomplete-url="/genres/search">
      <%= form.label :genre do %>
        Жанр
      <% end %>
      <input type="text" data-target="autocomplete.input" class="form-control" />
      <%= form.text_field :genre,type: 'hidden',data: { target: 'autocomplete.hidden'} %>
      <ul data-target="autocomplete.results"></ul>
    </div>
  </div>
  <h1>Главы</h1>
  <div data-controller="nested-form">
    <template data-target='nested-form.template'>
      <%= form.fields_for :chapters, Chapter.new, child_index: 'TEMPLATE_RECORD' do |chapter| %>
        <%= render 'chapter_fields',form: chapter %>
      <% end %>
    </template>
    <%= form.fields_for :chapters do |chapter| %>
      <%= render 'chapter_fields',form: chapter %>
    <% end %>
    <div data-target="nested-form.add_chapter">
      <%= link_to "Добавить главу","#",data: { action: "click->nested-form#add_association"} %>
    </div>
  </div>
  <div class="form-group">
    <%= form.submit 'Создать', class: "btn btn-success"%>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center mb-5">Фанфики</h1>

<% @posts.each do |post| %>
  <div class="jumbotron">
    <h3 class="text-center"><%= link_to post.title,post_path(post) %></h3>
    <p><%= post.summary %></p>
    <hr>
    <div class="row d-flex justify-content-between">
      <div class="col d-flex justify-content-around">
        <small>Кол-во глав: <%= post.chapters.count %></small>
        <small>Средняя оценка: <%= rand(5) %></small>
      </div>
      <div class="col d-flex justify-content-around">
        <% if user_signed_in? && current_user.id == post.user_id %>
          <%= link_to 'Редактировать',edit_post_path(post) %>
          <%= link_to 'Удалить',post_path(post),method: :delete, data: { confirm: 'Вы уверены?'} %>
        <% end %>
      </div>
    </div>

  </div>

<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Назад', posts_path %>

app/views/posts/search.html.erb
search.html.erb

app/views/posts/show.html.erb
<div class="jumbotron post" data-post-id="<%= @post.id %>">
	<h1 class="text-center">Название: <%= @post.title %></h1>
	<p>
	  <h2 class="text-center">Краткое содержание: <%= @post.summary %></h2>
	  
	</p>
	<p>
		<h3>Оглавление:</h3>
		<ul>	
		<% @post.chapters.each do |chapter| %>
			<li><%= link_to chapter.title, "##{dom_id(chapter)}" %></li>
			<hr>
		<% end %>
		</ul>

	</p>
	<p>
		<% @post.chapters.each.with_index do |chapter,i| %>
			<h1 class="text-center" id="<%= dom_id(chapter) %>">
				Глава <%= i + 1 %>. <%= chapter.title %>
			</h1>
			<p>
				<%= chapter.content %>
			</p>
			<hr>
			<% if user_signed_in? && !chapter.liked?(current_user) %>
				<%= link_to 'Мне понравилась эта глава',chapter_like_path(chapter_id: chapter.id,user_id: current_user.id),method: :post %>
			<% elsif user_signed_in? %>
				<span>Вы уже оценили эту главу</span>
			<% end %>
		<% end %>
	</p>

	<% if user_signed_in? && current_user.id == @post.user_id %>
		<%= link_to 'Редактировать',edit_post_path(@post) %> |
	<% end %>
	<%= link_to 'Назад', posts_path %>
</div>
<h1 class="text-center">
	Комментарии:
</h1>

<%= form_for Comment.new,remote: true do |f| %>
	<%= f.text_field :post_id,type: 'hidden',value: @post.id %>
	<div class="form-group">
		<%= f.text_area :content,class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.submit 'Добавить', class: 'btn btn-success' %>
	</div>
<% end %>

<div class="comments">
	<% @post.comments.each do |comment| %>
		<div class="jumbotron">
			<div class="row mb-3">
				<div class="col-6">
					<%= comment.user.first_name %> <%= comment.user.last_name %>
				</div>
				<div class="col-6 d-flex justify-content-end">
					<%= link_to comment.user.email,user_profile_path(comment.user) %>
				</div>
			</div>
			<div class="row">
				<div class="col">
					<%= comment.content %>
				</div>
			</div>
		</div>
	<% end %>
</div>

app/views/users/profile.html.erb
<div class="mt-5">
	<div class="row mb-5 jumbotron" data-controller="user">
		<div class="col-4">
			<% if @user.avatar.attached? %>
				<%= image_tag @user.avatar %>
			<% end %>
		</div>
		<div class="col-8">
			<p>
				<strong>Электронная почта:</strong> <span data-target="user.email"><%= @user.email %></span>
			</p>
			<p>
				<strong>Имя: </strong> <span data-target="user.first_name"><%= @user.first_name %></span>
			</p>
			<p>
				<strong>Фамилия: </strong> <span data-target="user.last_name"><%= @user.last_name %></span>
			</p>
			<% if user_signed_in? && current_user.id == @user.id %>
				<button class="btn btn-success" data-action="click->user#render_form">Редактировать</button>
			<% end %>
		</div>
	</div>
	<h2 class="text-center mb-3">Список постов пользователя</h2>
	<table class="table">
	  <thead>
	    <tr>
	      <th scope="col">#</th>
	      <th scope="col">Название</th>
	      <th scope="col">Краткое описание</th>
	      <th scope="col">Кол-во глав</th>
	      <th scope="col">Действия</th>
	    </tr>
	  </thead>
	  <tbody>
	  	<% @user.posts.each do |post| %>
			<tr>
				<th scope="row"><%= post.id %></th>
				<td><%= post.title %></td>
				<td><%= post.summary %></td>
				<td><%= post.chapters.count %></td>
				<td>
					<%= link_to 'Читать',post_path(post) %>
					<% if user_signed_in? && @user.id == current_user.id %>
						<%= link_to 'Ред.',edit_post_path(post) %>
						<%= link_to 'Удалить',post_path(post),method: :delete %>
					<% end %>
				</td>
			</tr>
	  	<% end %>
	  </tbody>
	</table>
	<% if user_signed_in? && current_user.id == @user.id %>
		<%= link_to 'Создать пост',new_post_path %>
	<% end %>
</div>